/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aispeech_tts_MP3Decoder */

#ifndef _Included_com_aispeech_tts_MP3Decoder
#define _Included_com_aispeech_tts_MP3Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aispeech_tts_MP3Decoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aispeech_tts_MP3Decoder_init
  (JNIEnv *, jclass);

/*
 * Class:     com_aispeech_tts_MP3Decoder
 * Method:    decode
 * Signature: ([BI[S[S)I
 */
JNIEXPORT jint JNICALL Java_com_aispeech_tts_MP3Decoder_decode
  (JNIEnv *, jclass, jbyteArray, jint, jshortArray, jshortArray);

/*
 * Class:     com_aispeech_tts_MP3Decoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_aispeech_tts_MP3Decoder_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
